// Build the browser engine: release Wasm for `sloppy-web`, then its wasm-bindgen
// glue into the ignored `src/generated/engine/`. Pages import
// `src/generated/engine/engine.js` and the binary through Vite's `?url`, and
// initialize with `init({ module_or_path: wasmUrl })`. Vite does not compile Rust:
// rerun this after Rust or WGSL edits.
//
// Cargo runs from the repository root so `.cargo/config.toml` (SIMD) applies.
// Setup: rustup's wasm32-unknown-unknown target and `wasm-bindgen-cli` 0.2.129,
// matching the `wasm-bindgen` crate pin.
//
// Like the server build, the Wasm is stamped with the content version clients and the
// server must share (`SLOPPY_CONTENT_VERSION`): multiplayer joins send it. The same stamp
// goes to `src/generated/engine/content-version.js` for Battle Setup's room list, which
// runs before the engine loads.
//
// `--labs` adds the development labs (`RenderLab`, `EffectsLab`, the `labs` feature of
// `sloppy-web`) and writes their glue to `src/generated/engine-labs/` instead, so a lab
// build never replaces the production engine that the game, `pnpm run build` and the dev
// server load.
import { spawnSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { contentVersion } from "./content-version.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const labs = process.argv.includes("--labs");
const outDir = labs ? "src/generated/engine-labs" : "src/generated/engine";
const version = await contentVersion();
const steps = [
  [
    "cargo",
    [
      "build",
      "--locked",
      "--release",
      "--target",
      "wasm32-unknown-unknown",
      "-p",
      "sloppy-web",
      ...(labs ? ["--features", "labs"] : []),
    ],
  ],
  [
    "wasm-bindgen",
    [
      "target/wasm32-unknown-unknown/release/sloppy_web.wasm",
      "--target",
      "web",
      "--out-dir",
      outDir,
      "--out-name",
      "engine",
    ],
  ],
];
for (const [command, args] of steps) {
  const result = spawnSync(command, args, {
    cwd: root,
    stdio: "inherit",
    env: { ...process.env, SLOPPY_CONTENT_VERSION: version },
  });
  if (result.error) {
    console.error(
      `${command}: ${result.error.message}. Install Rust with the wasm32-unknown-unknown target and wasm-bindgen-cli 0.2.129.`,
    );
  }
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}
const stamp = fileURLToPath(new URL(`../${outDir}/content-version`, import.meta.url));
await writeFile(
  `${stamp}.js`,
  "// Generated by scripts/build-wasm.mjs: the content version this engine joins with.\n" +
    `export const CONTENT_VERSION = ${JSON.stringify(version)};\n`,
);
await writeFile(`${stamp}.d.ts`, "export declare const CONTENT_VERSION: string;\n");
