// Build the browser engine: release Wasm for `sloppy-web`, then its wasm-bindgen
// glue into the ignored `src/generated/engine/`. Pages import
// `src/generated/engine/engine.js` and the binary through Vite's `?url`, and
// initialize with `init({ module_or_path: wasmUrl })`. Vite does not compile Rust:
// rerun this after Rust or WGSL edits.
//
// A second build renders with WebGL2 instead of WebGPU (`sloppy-web`'s `webgl`
// feature) into `src/generated/engine-webgl/engine-webgl.js` and `engine-webgl_bg.wasm`;
// src/engine.ts loads it only where WebGPU is unavailable. Its own file names keep its
// binary apart from the WebGPU one in the bundle. The two builds run at once, the WebGL
// one in its own target directory (`target/webgl`): most of each is a final link-time
// optimization that uses one core.
//
// Cargo runs from the repository root so `.cargo/config.toml` (SIMD) applies.
// Setup: rustup's wasm32-unknown-unknown target and `wasm-bindgen-cli` 0.2.129,
// matching the `wasm-bindgen` crate pin.
//
// Like the server build, the Wasm is stamped with the content version clients and the
// server must share (`SLOPPY_CONTENT_VERSION`): multiplayer joins send it. The same stamp
// goes to `src/generated/engine/content-version.js` for Battle Setup's room list, which
// runs before the engine loads.
//
// `--labs` adds the development labs (`RenderLab`, `EffectsLab`, the `labs` feature of
// `sloppy-web`) and writes their glue to `src/generated/engine-labs/` instead, so a lab
// build never replaces the production engine that the game, `pnpm run build` and the dev
// server load.
import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { contentVersion } from "./content-version.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const labs = process.argv.includes("--labs");
const outDir = labs ? "src/generated/engine-labs" : "src/generated/engine";
const version = await contentVersion();

/** Run `command` from the repository root; rejects unless it succeeds. */
function run(command, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: root,
      stdio: "inherit",
      env: { ...process.env, SLOPPY_CONTENT_VERSION: version },
    });
    child.on("error", (error) =>
      reject(
        new Error(
          `${command}: ${error.message}. Install Rust with the wasm32-unknown-unknown target and wasm-bindgen-cli 0.2.129.`,
        ),
      ),
    );
    child.on("exit", (status) =>
      status === 0 ? resolve() : reject(new Error(`${command} exited with ${status}`)),
    );
  });
}

/** Build `sloppy-web` with `features` in `targetDir`, then write its glue as `outName`
 * in `dir`. */
async function buildEngine({ features, targetDir, dir, outName }) {
  await run("cargo", [
    "build",
    "--locked",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "--target-dir",
    targetDir,
    "-p",
    "sloppy-web",
    ...features,
  ]);
  await run("wasm-bindgen", [
    `${targetDir}/wasm32-unknown-unknown/release/sloppy_web.wasm`,
    "--target",
    "web",
    "--out-dir",
    dir,
    "--out-name",
    outName,
  ]);
}

const engines = labs
  ? [{ features: ["--features", "labs"], targetDir: "target", dir: outDir, outName: "engine" }]
  : [
      { features: [], targetDir: "target", dir: outDir, outName: "engine" },
      {
        features: ["--no-default-features", "--features", "webgl"],
        targetDir: "target/webgl",
        dir: "src/generated/engine-webgl",
        outName: "engine-webgl",
      },
    ];
// Cargo creates a missing target directory under a temporary name and renames it into
// place, so on a fresh checkout the outer build could replace `target/` while the
// inner one works in it. Both exist before either build starts.
for (const { targetDir } of engines) {
  await mkdir(fileURLToPath(new URL(`../${targetDir}`, import.meta.url)), { recursive: true });
}
const results = await Promise.allSettled(engines.map(buildEngine));
const failure = results.find((result) => result.status === "rejected");
if (failure) {
  console.error(failure.reason.message);
  process.exit(1);
}
const stamp = fileURLToPath(new URL(`../${outDir}/content-version`, import.meta.url));
await writeFile(
  `${stamp}.js`,
  "// Generated by scripts/build-wasm.mjs: the content version this engine joins with.\n" +
    `export const CONTENT_VERSION = ${JSON.stringify(version)};\n`,
);
await writeFile(`${stamp}.d.ts`, "export declare const CONTENT_VERSION: string;\n");
